// Local fixture dataset — used only when USE_FIXTURE=1 (dev/visual iteration).
// Mirrors the real Actores schema (Escala / Place / location_lat / location_lng)
// and the Intervenciones fields, so the defensive matching in records.ts is
// exercised the same way real Notion data is.
//
// Territory: the Altiplano Estepario (Granada / Almería / Murcia steppe highlands).
// Towns are real with approximate coordinates; organisations are illustrative.

import type { NormalizedRecord } from './notion';

function rec(partial: Omit<NormalizedRecord, 'id' | 'url' | 'createdTime' | 'lastEditedTime'>): NormalizedRecord {
  return {
    id: partial.properties['ID'] as string,
    url: `https://www.notion.so/fixture-${partial.properties['ID']}`,
    createdTime: '2026-01-01T00:00:00.000Z',
    lastEditedTime: '2026-01-01T00:00:00.000Z',
    ...partial,
  };
}

export const FIXTURE_ORGANIZATIONS: NormalizedRecord[] = [
  rec({
    properties: {
      ID: 'org-jiloca',
      Name: 'Asociación de Pastores del Altiplano',
      'Descripción': 'Red de ganaderos extensivos que comparte pastos, formación y rutas de trashumancia en el altiplano.',
      Web: 'https://pastoresaltiplano.example.com',
      Place: { name: 'Baza', latitude: 37.4907, longitude: -2.7726 },
      location_lat: 37.4907,
      location_lng: -2.7726,
      Tipo: 'Asociación',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': true,
    },
  }),
  rec({
    properties: {
      ID: 'org-almendra',
      Name: 'Cooperativa Agroecológica del Altiplano',
      'Descripción': 'Almendra, olivar y cereal ecológico de secano con circuitos cortos de comercialización.',
      Web: 'https://agroaltiplano.example.com',
      Place: { name: 'Cúllar', latitude: 37.582, longitude: -2.5753 },
      location_lat: 37.582,
      location_lng: -2.5753,
      Tipo: 'Cooperativa',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': true,
    },
  }),
  rec({
    properties: {
      ID: 'org-estepa',
      Name: 'Estepa Viva — Custodia del Territorio',
      'Descripción': 'Conservación de estepas, alcaravanes y sisones mediante acuerdos de custodia con agricultores y ganaderos.',
      Web: 'https://estepaviva.example.com',
      Place: { name: 'Huéscar', latitude: 37.8099, longitude: -2.5413 },
      location_lat: 37.8099,
      location_lng: -2.5413,
      Tipo: 'Fundación',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': true,
    },
  }),
  rec({
    properties: {
      ID: 'org-huerta',
      Name: 'Colectivo Huerta de Guadix',
      'Descripción': 'Huertos comunitarios y banco de tierras para jóvenes agricultores en las vegas del altiplano.',
      Web: 'https://huertaguadix.example.com',
      Place: { name: 'Guadix', latitude: 37.3013, longitude: -3.136 },
      location_lat: 37.3013,
      location_lng: -3.136,
      Tipo: 'Colectivo',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': true,
    },
  }),
  rec({
    properties: {
      ID: 'org-semillas',
      Name: 'Red de Semillas del Altiplano',
      'Descripción': 'Banco comunitario de semillas de variedades locales adaptadas al secano frío: trigo escaña, lenteja, garbanzo.',
      Web: 'https://semillasaltiplano.example.com',
      Place: { name: 'Caniles', latitude: 37.4362, longitude: -2.7246 },
      location_lat: 37.4362,
      location_lng: -2.7246,
      Tipo: 'Red',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': true,
    },
  }),
  rec({
    properties: {
      ID: 'org-parque',
      Name: 'Parque Natural Sierra de María–Los Vélez',
      'Descripción': 'Espacio protegido del altiplano: restauración de ecosistemas, educación ambiental y uso público.',
      Web: 'https://sierramaria.example.com',
      Place: { name: 'María', latitude: 37.71, longitude: -2.166 },
      location_lat: 37.71,
      location_lng: -2.166,
      Tipo: 'Parque natural',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': true,
    },
  }),
  rec({
    properties: {
      ID: 'org-bardera',
      Name: 'Asociación Cultural La Bardera',
      'Descripción': 'Cultura rural y memoria del territorio: archivos orales, rutas etnográficas y teatro comunitario.',
      Web: 'https://labardera.example.com',
      Place: { name: 'Galera', latitude: 37.7446, longitude: -2.55 },
      location_lat: 37.7446,
      location_lng: -2.55,
      Tipo: 'Asociación',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': false,
    },
  }),
  rec({
    properties: {
      ID: 'org-pastores',
      Name: 'Escuela de Pastores del Altiplano',
      'Descripción': 'Formación profesional en ganadería extensiva, trashumancia moderna y elaboración de quesos de pasto.',
      Web: 'https://escuelapastores.example.com',
      Place: { name: 'Benamaurel', latitude: 37.6086, longitude: -2.7022 },
      location_lat: 37.6086,
      location_lng: -2.7022,
      Tipo: 'Fundación',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': false,
    },
  }),
  rec({
    properties: {
      ID: 'org-vivero',
      Name: 'Vivero Forestal El Sabinar',
      'Descripción': 'Producción de planta autóctona y restauración de sabinares, encinares y bosques de ribera.',
      Web: 'https://elsabinar.example.com',
      Place: { name: 'Castilléjar', latitude: 37.72, longitude: -2.642 },
      location_lat: 37.72,
      location_lng: -2.642,
      Tipo: 'Empresa',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': false,
    },
  }),
  rec({
    properties: {
      ID: 'org-turismo',
      Name: 'Turismo Regenerativo Los Vélez',
      'Descripción': 'Alojamientos rurales y experiencias que financian la restauración de pastos y bosques del entorno.',
      Web: 'https://turismoregen.example.com',
      Place: { name: 'Vélez-Rubio', latitude: 37.647, longitude: -2.075 },
      location_lat: 37.647,
      location_lng: -2.075,
      Tipo: 'Iniciativa',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': false,
    },
  }),
  rec({
    properties: {
      ID: 'org-aguas',
      Name: 'Comunidad de Aguas de Zújar',
      'Descripción': 'Gestión colectiva del regadío histórico y acuerdos con la avifauna de la comarca.',
      Place: { name: 'Zújar', latitude: 37.545, longitude: -2.842 },
      location_lat: 37.545,
      location_lng: -2.842,
      Tipo: 'Comunidad',
      Escala: 'Altiplano Estepario',
      'Grupo de trabajo': false,
    },
  }),
  // --- Excluded by the filters (they demonstrate the inclusion rules) ---
  rec({
    properties: {
      ID: 'persona-maria',
      Name: 'María Pérez',
      'Descripción': 'Consultora agroecológica independiente.',
      Tipo: 'Persona',
      Escala: 'Altiplano Estepario',
      location_lat: 37.4907,
      location_lng: -2.7726,
    },
  }),
  rec({
    properties: {
      ID: 'persona-jose',
      Name: 'José Luis García',
      'Descripción': 'Pastor freelance.',
      Tipo: 'Individual',
      Escala: 'Altiplano Estepario',
      location_lat: 37.3013,
      location_lng: -3.136,
    },
  }),
  rec({
    properties: {
      ID: 'org-granada',
      Name: 'Fundación Regenera Granada',
      'Descripción': 'Fundación provincial con sede en la capital.',
      Tipo: 'Fundación',
      Escala: 'Provincial',
      location_lat: 37.1773,
      location_lng: -3.5986,
    },
  }),
  rec({
    properties: {
      ID: 'org-nacional',
      Name: 'Red Estatal de Pastos',
      'Descripción': 'Red de ámbito estatal.',
      Tipo: 'Red',
      Escala: 'Nacional',
      location_lat: 40.4168,
      location_lng: -3.7038,
    },
  }),
];

export const FIXTURE_INTERVENTIONS: NormalizedRecord[] = [
  rec({
    properties: {
      ID: 'int-1',
      Name: 'Refugios y pasos de ganado para la trashumancia',
      'Descripción': 'Recuperación de rutas pecuarias con refugios para pastores y pasos seguros para el rebaño.',
      Organización: ['org-jiloca'],
      'Área de trabajo': 'Agricultura regenerativa',
      'Valor ajustado a 5 años': 420000,
      '¿Es viable comercialmente?': 'Sí',
      'Financiación total': 200000,
      'Número de años': 4,
      Recurrente: true,
      'Tipo de capital 1': 'Capital natural',
      'Tipo de capital 2': 'Capital humano',
    },
  }),
  rec({
    properties: {
      ID: 'int-2',
      Name: 'Almazara comunitaria de secano',
      'Descripción': 'Almazara cooperativa que transforma la aceituna ecológica y devuelve el orujo como compost a las fincas.',
      Organización: ['org-almendra'],
      'Área de trabajo': 'Agricultura regenerativa',
      'Valor ajustado a 5 años': 850000,
      '¿Es viable comercialmente?': 'Sí',
      'Financiación total': 320000,
      'Número de años': 5,
      Recurrente: false,
      'Tipo de capital 1': 'Capital social',
      'Tipo de capital 2': 'Capital intelectual',
    },
  }),
  rec({
    properties: {
      ID: 'int-3',
      Name: 'Custodia territorial esteparia',
      'Descripción': 'Acuerdos de custodia con 12 fincas para dejar bordas y barbechos que alimenten a sisones y avutardas.',
      Organización: ['org-estepa'],
      'Área de trabajo': 'Espacios naturales',
      'Valor ajustado a 5 años': 300000,
      '¿Es viable comercialmente?': 'No',
      'Financiación total': 440000,
      'Número de años': 6,
      Recurrente: true,
      'Tipo de capital 1': 'Capital financiero',
      'Tipo de capital 2': 'Capital construido',
    },
  }),
  rec({
    properties: {
      ID: 'int-4',
      Name: 'Banco de tierras del altiplano',
      'Descripción': 'Plataforma que conecta propietarios jubilados con jóvenes agricultores mediante arrendamientos largos.',
      Organización: ['org-huerta'],
      'Área de trabajo': 'Articulación y desarrollo territorial',
      'Valor ajustado a 5 años': 180000,
      '¿Es viable comercialmente?': 'Sí',
      'Financiación total': 560000,
      'Número de años': 3,
      Recurrente: false,
      'Tipo de capital 1': 'Capital natural',
      'Tipo de capital 2': 'Capital humano',
    },
  }),
  rec({
    properties: {
      ID: 'int-5',
      Name: 'Red de semillas y multiplicación local',
      'Descripción': 'Multiplicación de escaña, lenteja pardina y garbanzo por agricultores socios; venta a panaderías locales.',
      Organización: ['org-semillas'],
      'Área de trabajo': 'Agricultura regenerativa',
      'Valor ajustado a 5 años': 240000,
      '¿Es viable comercialmente?': 'Sí',
      'Financiación total': 680000,
      'Número de años': 4,
      Recurrente: true,
      'Tipo de capital 1': 'Capital social',
      'Tipo de capital 2': 'Capital intelectual',
    },
  }),
  rec({
    properties: {
      ID: 'int-6',
      Name: 'Oficina de proyectos contra la despoblación',
      'Descripción': 'Ventanilla única comarcal para emprendedores rurales: acompañamiento, financiación y suelo.',
      Organización: ['org-parque'],
      'Área de trabajo': 'Articulación y desarrollo territorial',
      'Valor ajustado a 5 años': 150000,
      '¿Es viable comercialmente?': 'No',
      'Financiación total': 800000,
      'Número de años': 5,
      Recurrente: false,
      'Tipo de capital 1': 'Capital financiero',
      'Tipo de capital 2': 'Capital construido',
    },
  }),
  rec({
    properties: {
      ID: 'int-7',
      Name: 'Escuela de verano del territorio',
      'Descripción': 'Programa educativo anual que acerca a escolares y jóvenes a los oficios rurales y la biodiversidad esteparia.',
      Organización: ['org-bardera'],
      'Área de trabajo': 'Educación, cultura y turismo',
      'Valor ajustado a 5 años': 95000,
      '¿Es viable comercialmente?': 'No',
      'Financiación total': 920000,
      'Número de años': 6,
      Recurrente: true,
      'Tipo de capital 1': 'Capital natural',
      'Tipo de capital 2': 'Capital humano',
    },
  }),
  rec({
    properties: {
      ID: 'int-8',
      Name: 'Quesería de pasto del altiplano',
      'Descripción': 'Quesería artesanal con leche de la escuela de pastores; maduración y venta directa y a hostelería.',
      Organización: ['org-pastores'],
      'Área de trabajo': 'Agricultura regenerativa',
      'Valor ajustado a 5 años': 600000,
      '¿Es viable comercialmente?': 'Sí',
      'Financiación total': 1040000,
      'Número de años': 3,
      Recurrente: false,
      'Tipo de capital 1': 'Capital social',
      'Tipo de capital 2': 'Capital intelectual',
    },
  }),
  rec({
    properties: {
      ID: 'int-9',
      Name: 'Restauración de sabinares y encinares',
      'Descripción': 'Recuperación de masas de sabina y encina con planta autóctona del vivero y seguimiento ecológico.',
      Organización: ['org-vivero'],
      'Área de trabajo': 'Espacios naturales',
      'Valor ajustado a 5 años': 380000,
      '¿Es viable comercialmente?': 'No',
      'Financiación total': 1160000,
      'Número de años': 4,
      Recurrente: true,
      'Tipo de capital 1': 'Capital financiero',
      'Tipo de capital 2': 'Capital construido',
    },
  }),
  rec({
    properties: {
      ID: 'int-10',
      Name: 'Rutas del pastoreo regenerativo',
      'Descripción': 'Experiencias turísticas guiadas por pastores que financian la mejora de pastos y la conservación del paisaje.',
      Organización: ['org-turismo', 'org-aguas'],
      'Área de trabajo': 'Educación, cultura y turismo',
      'Valor ajustado a 5 años': 210000,
      '¿Es viable comercialmente?': 'Sí',
      'Financiación total': 1280000,
      'Número de años': 5,
      Recurrente: false,
      'Tipo de capital 1': 'Capital natural',
      'Tipo de capital 2': 'Capital humano',
    },
  }),
];