// UI strings for the interactive part of the simulator (charts, tables, KPIs).
// Functions take values already formatted by the caller.
export const STR = {
  es: {
    loc: "es-ES",
    threshold: "umbral",
    cumulativeLbl: "acumulado",
    // finca
    kGross: "Coste bruto de la transición", kGrossNote: "prácticas + servicios + inversión + pérdidas, 10 años",
    kPeak: "Necesidad máxima de financiación", kPeakNote: (tot, ha) => `${tot} para una finca de ${ha} ha`,
    kNet: "Resultado neto a 10 años", kNetNote: (van) => `VAN ${van}/ha`,
    kPayback: "Año de recuperación", yearN: (n, y) => `Año ${n} (${y})`, noPayback: "No en 10 años", kPaybackNote: "el acumulado vuelve a ser positivo",
    tNet: "neto del año", tCum: "acumulado", tAdopt: "adopción", t10: "10 años, €/ha", netResult: "Resultado neto",
    thItem: "Partida (€/ha)", thTotal: "Total", rowNet: "Neto", rowCum: "Acumulado",
    baseline: (kg, price, inc, margin) => `Línea base: ${kg} kg/ha × ${price} €/kg = <strong>${inc}/ha</strong> de ingreso; margen en caja actual <strong>${margin}/ha</strong> (incluye ayuda básica PAC).`,
    // credit
    pctFin: "% financiado", rate: "Tipo de interés", term: "Plazo (años)", grace: "Carencia (años)", farmSize: "Tamaño de finca (ha)",
    years: (v) => `${v} años`, ha: (v) => `${v} ha`,
    cLoan: "Importe del préstamo", cLoanNote: (ha, need, pct) => `${ha} ha × ${need}/ha × ${pct}`,
    cPay: "Cuota anual tras carencia",
    cDscr: "DSCR mínimo", meets: "cumple", notMeets: "no cumple", cThresh: (v) => `umbral ${v}×`,
    cMargin: "Margen en caja actual", cMarginNote: (v) => `${v}/ha antes de la transición`,
    noPay: "sin cuota", tCash: "caja disponible", tDebt: "servicio de la deuda", tBalance: "saldo vivo",
    noDebt: "No hay deuda que cubrir: la transición no genera necesidad de financiación en este escenario.",
    warnNeg: "<strong>Margen actual negativo.</strong> Con los costes de referencia (MAPA/Junta), esta finca tipo no genera caja para pagar deuda con su actividad actual. El repago dependería de otras rentas (otros cultivos, ganadería, PAC no incluida) o de financiación no reembolsable. Revisar con datos reales de fincas del Altiplano.",
    warnLow: "<strong>La cobertura no llega al umbral.</strong> Prueba con más carencia, más plazo, menos % financiado (subvención o capital catalítico para el resto) o un nivel de transición menos intenso.",
    // landscape
    uptake: "Captación en 10 años", almond: "Almendro (ha)", olive: "Olivar (ha)", cereal: "Cereal (ha)", pistachio: "Pistacho (ha)",
    lHa: "Hectáreas en transición", lFarms: (n) => `${n} fincas aprox.`,
    lGross: "Coste bruto de la transición", lGrossNote: "suma de costes, sin descontar ingresos",
    lNeed: "Necesidad de financiación", lNeedNote: "pico acumulado por finca × hectáreas",
    lDemand: "Demanda potencial de crédito", lDemandNote: (p) => `con ${p} financiado con deuda`,
    tNeed: "necesidad", tHa: "hectáreas",
    thFarm: "Finca tipo", thHectares: "Hectáreas", thFarms: "Fincas", thNeedHa: "Necesidad €/ha", thNeedTotal: "Necesidad total", thNpv: "VAN €/ha", thRecovery: "Recuperación",
    yearShort: (n) => `año ${n}`, over10: "> 10 años", total: "Total",
    landNote: "El <em>coste bruto</em> suma todos los costes de la transición; la <em>necesidad de financiación</em> es menor porque descuenta ayudas, ahorros y primas a medida que llegan.",
    // sensitivity
    npv: "VAN", confidence: (c) => `confianza ${c}`, withLow: (v) => `con el valor bajo (${v})`, withHigh: (v) => `con el valor alto (${v})`, tConf: "confianza",
    // assumptions
    anyCrop: "Cualquiera",
    thParam: "Parámetro", thLow: "Bajo", thCentral: "Central", thHigh: "Alto", thUnit: "Unidad", thSource: "Fuente", thType: "Tipo", thConf: "Confianza",
    thPractice: "Práctica", thCrops: "Cultivos", thCoverage: "Cobertura", thEvery: "Cada", thYears: "Años",
    onlyBase: (b) => `solo ${b}`, everyN: (n) => `${n} a.`, thCurve: "Curva",
    meta: (d, p, pr) => `Datos actualizados ${d} · ${p} parámetros · ${pr} prácticas`,
    metaLonja: (w, y) => ` · almendra Lonja de Murcia sem. ${w}/${y}`,
    pConv: (u) => `Precio convencional (${u})`, pEco: (u) => `Precio ecológico (${u})`,
    pPremEco: "Prima ecológica (% s/ convencional)", pRegen: "Sobreprecio regenerativo (% s/ ecológico)",
    refLonja: (c0, c1, lo, hi, mid, w, y, now) => `Lonja de Murcia, campañas ${c0}–${c1}: ${lo}–${hi} €, media ${mid} €. Actual (sem. ${w}/${y}): <b>${now} €</b>`,
    useCurrent: "usar",
    pPse: "Pagos por servicios ecosistémicos (€/ha/año)",
    refPse: (ref) => `Carbono, agua u otros servicios pagados por un tercero, desde el año 3. Referencia carbono para este cultivo: ≈${ref} €/ha/año (secuestro × precio, menos verificación).`,
    sum: (cultivo, partes) => `${cultivo}: ${partes.join(" · ")}`,
    sConv: "precio convencional", sEco: "precio ecológico", sPremEco: "prima ecológica", sRegen: "sobreprecio regenerativo", sPse: "servicios ecosistémicos",
    perHaYr: "€/ha/año",
    sDiv: "diversificación", yr: "año",
    sDivTip: "Media anual en 10 años de los pagos por servicios ecosistémicos y de los módulos de diversificación (ingresos y ahorros menos costes e inversión), por hectárea en transición.",
    refRegen: "Comercializadoras del territorio: media ≈3,3 %, máximo 5–6 %. Solo con certificado.",
    refRange: (lo, hi, c) => `Rango del supuesto: ${lo}–${hi} · confianza ${c}.`,
    thSeason: "Campaña", thComuna: "Comuna", thEco: "Ecológica", thEcoDiff: "Diferencia eco.",
    currentWeek: (w, y) => `Actual · sem. ${w}/${y}`, sources: "Fuentes", currentSrc: "Precio actual",
    lines: {
      rendimiento: "Cambio de rendimiento", prima_eco: "Prima ecológica (conv. certificada)", prima_regen: "Sobreprecio regenerativo", ecorregimen: "Ecorrégimen PAC",
      ayuda_eco: "Ayuda agricultura ecológica (PAC)", carbono: "Pagos por servicios ecosistémicos", fertilizacion: "Fertilización sustituida", fitosanitarios: "Menos fitosanitarios",
      laboreo: "Menos laboreo y combustible", practicas: "Prácticas recurrentes", servicios: "Servicios técnicos", capex: "Inversiones iniciales", reserva: "Superficie para biodiversidad", diversificacion: "Diversificación",
    },
    expandAll: "Abrir todo", collapseAll: "Cerrar todo",
    thItemU: (u) => (u === "ha" ? "Partida (€/ha)" : "Partida (€ por finca)"),
    kPeakNoteFarm: (perHa, haT, ha) => `${perHa}/ha de finca · ${haT} de ${ha} ha en transición`,
    kGrossNoteU: (otro) => `${otro} · prácticas + servicios + inversión + pérdidas, 10 años`,
    kNetNoteU: (van, otro) => `VAN ${van} · ${otro}`,
    perHaOf: (v) => `${v}/ha de finca`, forFarm: (v, ha) => `${v} para la finca de ${ha} ha`,
    cLoanNote2: (need, p) => `necesidad máxima ${need} × ${p}`,
    divOff: "sin diversificación", divNone: "No hay módulos de diversificación para este cultivo.",
    divShare: (n) => `${n} (% de las ha en transición)`,
    divRef: (inv, coste, ing, anio, ahorro, rend, conf) => `Inversión ${inv} €/ha · coste ${coste} €/ha/año · ingreso ${ing} €/ha/año desde el año ${anio}${ahorro}${rend} · confianza ${conf}.`,
    divAhorro: (c, e) => ` · ahorra ${c} del manejo de cubierta${e ? ` y ${e} de las enmiendas` : ""}`,
    divRend: (r) => ` · rendimiento del cultivo +${r}`,
    thInUse: "En uso", thRange: "Rango (bajo–alto)", adjusted: "ajustado", nRows: (n) => `${n}`,
    supCats: {}, inUseShare: (p) => `${p} de las ha`, notActive: "no activo",
    pracDetail: (cob, cada, anios) => `cobertura ${cob} · cada ${cada} · años ${anios}`,
    modRange: (inv, coste, ing) => `inversión ${inv} · coste ${coste} · ingreso ${ing} €/ha`,
    pseRow: "Pagos por servicios ecosistémicos", pseRange: (ref) => `0–150 · referencia carbono ≈${ref}`,
    thModule: "Módulo", thInv: "Inversión €/ha", thCost: "Coste €/ha/año", thIncome: "Ingreso €/ha/año", thFrom: "Desde año", thSaving: "Ahorro cubierta / enmiendas", thYield: "Efecto rendimiento",
    groups: {
      produccion: { name: "Producción y precio", hint: "cosecha, superficie retirada y primas de precio" },
      ayudas: { name: "Ayudas y otros ingresos", hint: "PAC y pagos por servicios ecosistémicos (carbono, agua…)" },
      ahorro: { name: "Ahorro en costes de cultivo", hint: "lo que la finca deja de gastar" },
      practicas: { name: "Prácticas regenerativas", hint: "coste anual de cada práctica" },
      servicios: { name: "Servicios técnicos", hint: "diseño, asesoría, seguimiento y certificación" },
      capex: { name: "Inversiones iniciales", hint: "pago único en los años 1–3: setos, cajas nido, zanjas, charcas, islas de biodiversidad" },
      diversificacion: { name: "Diversificación", hint: "ganadería, aromáticas o colmenas: ingresos, costes y ahorros" },
    },
  },
  en: {
    loc: "en-GB",
    threshold: "threshold",
    cumulativeLbl: "cumulative",
    kGross: "Gross cost of the transition", kGrossNote: "practices + services + investment + losses, 10 years",
    kPeak: "Peak financing need", kPeakNote: (tot, ha) => `${tot} for a ${ha} ha farm`,
    kNet: "Net result over 10 years", kNetNote: (van) => `NPV ${van}/ha`,
    kPayback: "Payback year", yearN: (n, y) => `Year ${n} (${y})`, noPayback: "Not within 10 years", kPaybackNote: "the cumulative total turns positive again",
    tNet: "net of the year", tCum: "cumulative", tAdopt: "adoption", t10: "10 years, €/ha", netResult: "Net result",
    thItem: "Item (€/ha)", thTotal: "Total", rowNet: "Net", rowCum: "Cumulative",
    baseline: (kg, price, inc, margin) => `Baseline: ${kg} kg/ha × ${price} €/kg = <strong>${inc}/ha</strong> revenue; current cash margin <strong>${margin}/ha</strong> (includes CAP basic support).`,
    pctFin: "% financed", rate: "Interest rate", term: "Term (years)", grace: "Grace period (years)", farmSize: "Farm size (ha)",
    years: (v) => `${v} years`, ha: (v) => `${v} ha`,
    cLoan: "Loan amount", cLoanNote: (ha, need, pct) => `${ha} ha × ${need}/ha × ${pct}`,
    cPay: "Annual repayment after grace period",
    cDscr: "Minimum DSCR", meets: "meets", notMeets: "does not meet", cThresh: (v) => `threshold ${v}×`,
    cMargin: "Current cash margin", cMarginNote: (v) => `${v}/ha before the transition`,
    noPay: "no repayment", tCash: "available cash", tDebt: "debt service", tBalance: "outstanding balance",
    noDebt: "There is no debt to cover: the transition does not create a financing need in this scenario.",
    warnNeg: "<strong>Negative current margin.</strong> With the reference costs (MAPA/Junta), this typical farm generates no cash to repay debt from its current activity. Repayment would depend on other income (other crops, livestock, CAP not included) or on non-repayable financing. Check against real farm data from the Altiplano.",
    warnLow: "<strong>Coverage does not reach the threshold.</strong> Try a longer grace period, a longer term, a lower % financed (grant or catalytic capital for the rest) or a less intensive transition level.",
    uptake: "Uptake over 10 years", almond: "Almond (ha)", olive: "Olive grove (ha)", cereal: "Cereal (ha)", pistachio: "Pistachio (ha)",
    lHa: "Hectares in transition", lFarms: (n) => `approx. ${n} farms`,
    lGross: "Gross cost of the transition", lGrossNote: "sum of costs, before deducting revenue",
    lNeed: "Financing need", lNeedNote: "cumulative peak per farm × hectares",
    lDemand: "Potential credit demand", lDemandNote: (p) => `with ${p} financed by debt`,
    tNeed: "need", tHa: "hectares",
    thFarm: "Typical farm", thHectares: "Hectares", thFarms: "Farms", thNeedHa: "Need €/ha", thNeedTotal: "Total need", thNpv: "NPV €/ha", thRecovery: "Payback",
    yearShort: (n) => `year ${n}`, over10: "> 10 years", total: "Total",
    landNote: "The <em>gross cost</em> adds up all transition costs; the <em>financing need</em> is lower because it nets off support, savings and premiums as they arrive.",
    npv: "NPV", confidence: (c) => `${c} confidence`, withLow: (v) => `at the low value (${v})`, withHigh: (v) => `at the high value (${v})`, tConf: "confidence",
    anyCrop: "Any",
    thParam: "Parameter", thLow: "Low", thCentral: "Central", thHigh: "High", thUnit: "Unit", thSource: "Source", thType: "Type", thConf: "Confidence",
    thPractice: "Practice", thCrops: "Crops", thCoverage: "Coverage", thEvery: "Every", thYears: "Years",
    onlyBase: (b) => `only ${b}`, everyN: (n) => `${n} y.`, thCurve: "Curve",
    meta: (d, p, pr) => `Data updated ${d} · ${p} parameters · ${pr} practices`,
    metaLonja: (w, y) => ` · almonds Lonja de Murcia wk ${w}/${y}`,
    pConv: (u) => `Conventional price (${u})`, pEco: (u) => `Organic price (${u})`,
    pPremEco: "Organic premium (% over conventional)", pRegen: "Regenerative premium (% over organic)",
    refLonja: (c0, c1, lo, hi, mid, w, y, now) => `Lonja de Murcia, seasons ${c0}–${c1}: €${lo}–${hi}, average €${mid}. Current (wk ${w}/${y}): <b>€${now}</b>`,
    useCurrent: "use",
    pPse: "Payments for ecosystem services (€/ha/year)",
    refPse: (ref) => `Carbon, water or other services paid for by a third party, from year 3. Carbon reference for this crop: ≈€${ref}/ha/year (sequestration × price, minus verification).`,
    sum: (crop, parts) => `${crop}: ${parts.join(" · ")}`,
    sConv: "conventional price", sEco: "organic price", sPremEco: "organic premium", sRegen: "regenerative premium", sPse: "ecosystem services",
    perHaYr: "€/ha/year",
    sDiv: "diversification", yr: "year",
    sDivTip: "Average per year over 10 years of payments for ecosystem services and diversification modules (income and savings minus costs and investment), per hectare in transition.",
    refRegen: "Local commercializers: average ≈3.3%, maximum 5–6%. Only with certification.",
    refRange: (lo, hi, c) => `Assumption range: ${lo}–${hi} · ${c} confidence.`,
    thSeason: "Season", thComuna: "Comuna", thEco: "Organic", thEcoDiff: "Organic difference",
    currentWeek: (w, y) => `Current · wk ${w}/${y}`, sources: "Sources", currentSrc: "Current price",
    lines: {
      rendimiento: "Yield change", prima_eco: "Organic premium (certified conv.)", prima_regen: "Regenerative premium", ecorregimen: "CAP eco-scheme",
      ayuda_eco: "Organic farming support (CAP)", carbono: "Payments for ecosystem services", fertilizacion: "Fertilization replaced", fitosanitarios: "Less plant protection",
      laboreo: "Less tillage and fuel", practicas: "Recurring practices", servicios: "Technical services", capex: "Upfront investments", reserva: "Area set aside for biodiversity", diversificacion: "Diversification",
    },
    expandAll: "Expand all", collapseAll: "Collapse all",
    thItemU: (u) => (u === "ha" ? "Item (€/ha)" : "Item (€ per farm)"),
    kPeakNoteFarm: (perHa, haT, ha) => `${perHa}/ha of farm · ${haT} of ${ha} ha in transition`,
    kGrossNoteU: (other) => `${other} · practices + services + investment + losses, 10 years`,
    kNetNoteU: (van, other) => `NPV ${van} · ${other}`,
    perHaOf: (v) => `${v}/ha of farm`, forFarm: (v, ha) => `${v} for the ${ha} ha farm`,
    cLoanNote2: (need, p) => `peak need ${need} × ${p}`,
    divOff: "no diversification", divNone: "There are no diversification modules for this crop.",
    divShare: (n) => `${n} (% of ha in transition)`,
    divRef: (inv, cost, inc, year, saving, yld, conf) => `Investment €${inv}/ha · cost €${cost}/ha/year · income €${inc}/ha/year from year ${year}${saving}${yld} · ${conf} confidence.`,
    divAhorro: (c, e) => ` · saves ${c} of cover-crop management${e ? ` and ${e} of amendments` : ""}`,
    divRend: (r) => ` · crop yield +${r}`,
    thInUse: "In use", thRange: "Range (low–high)", adjusted: "adjusted", nRows: (n) => `${n}`,
    supCats: { "Superficie": "Area", "Rendimiento": "Yield", "Precio": "Price", "Coste base": "Baseline cost", "PAC": "CAP", "Adopción": "Adoption", "Carbono": "Carbon", "Crédito": "Credit",
      "Prácticas regenerativas": "Regenerative practices", "Servicios técnicos": "Technical services", "Inversiones iniciales": "Upfront investments", "Diversificación": "Diversification" },
    inUseShare: (p) => `${p} of ha`, notActive: "not active",
    pracDetail: (cov, every, years) => `coverage ${cov} · every ${every} · years ${years}`,
    modRange: (inv, cost, inc) => `investment ${inv} · cost ${cost} · income ${inc} €/ha`,
    pseRow: "Payments for ecosystem services", pseRange: (ref) => `0–150 · carbon reference ≈${ref}`,
    thModule: "Module", thInv: "Investment €/ha", thCost: "Cost €/ha/year", thIncome: "Income €/ha/year", thFrom: "From year", thSaving: "Cover / amendment saving", thYield: "Yield effect",
    groups: {
      produccion: { name: "Production and price", hint: "harvest, land set aside and price premiums" },
      ayudas: { name: "Subsidies and other income", hint: "CAP and payments for ecosystem services (carbon, water…)" },
      ahorro: { name: "Savings on farming costs", hint: "what the farm stops spending" },
      practicas: { name: "Regenerative practices", hint: "yearly cost of each practice" },
      servicios: { name: "Technical services", hint: "design, advice, monitoring and certification" },
      capex: { name: "Upfront investments", hint: "one-off payment in years 1–3: hedgerows, nest boxes, swales, ponds, biodiversity islands" },
      diversificacion: { name: "Diversification", hint: "livestock, aromatics or beehives: income, costs and savings" },
    },
  },
};
