// UI strings for the interactive part of the simulator (charts, tables, KPIs).
// Functions take values already formatted by the caller.
export const STR = {
  es: {
    loc: "es-ES",
    threshold: "umbral",
    cumulativeLbl: "acumulado",
    // finca
    kGross: "Coste bruto de la transición", kGrossNote: "prácticas + servicios + inversión + pérdidas, 10 años",
    kPeak: "Necesidad máxima de financiación", kPeakNote: (tot, ha) => `${tot} para una finca de ${ha} ha`,
    kNet: "Resultado neto a 10 años", kNetNote: (van) => `VAN ${van}/ha`,
    kPayback: "Año de recuperación", yearN: (n, y) => `Año ${n} (${y})`, noPayback: "No en 10 años", kPaybackNote: "el acumulado vuelve a ser positivo",
    tNet: "neto del año", tCum: "acumulado", tAdopt: "adopción", t10: "10 años, €/ha", netResult: "Resultado neto",
    thItem: "Partida (€/ha)", thTotal: "Total", rowNet: "Neto", rowCum: "Acumulado",
    baseline: (kg, price, inc, margin) => `Línea base: ${kg} kg/ha × ${price} €/kg = <strong>${inc}/ha</strong> de ingreso; margen en caja actual <strong>${margin}/ha</strong> (incluye ayuda básica PAC).`,
    // credit
    pctFin: "% financiado", rate: "Tipo de interés", term: "Plazo (años)", grace: "Carencia (años)", farmSize: "Tamaño de finca (ha)",
    years: (v) => `${v} años`, ha: (v) => `${v} ha`,
    cLoan: "Importe del préstamo", cLoanNote: (ha, need, pct) => `${ha} ha × ${need}/ha × ${pct}`,
    cPay: "Cuota anual tras carencia",
    cDscr: "DSCR mínimo", meets: "cumple", notMeets: "no cumple", cThresh: (v) => `umbral ${v}×`,
    cMargin: "Margen en caja actual", cMarginNote: (v) => `${v}/ha antes de la transición`,
    noPay: "sin cuota", tCash: "caja disponible", tDebt: "servicio de la deuda", tBalance: "saldo vivo",
    noDebt: "No hay deuda que cubrir: la transición no genera necesidad de financiación en este escenario.",
    warnNeg: "<strong>Margen actual negativo.</strong> Con los costes de referencia (MAPA/Junta), esta finca tipo no genera caja para pagar deuda con su actividad actual. El repago dependería de otras rentas (otros cultivos, ganadería, PAC no incluida) o de financiación no reembolsable. Revisar con datos reales de fincas del Altiplano.",
    warnLow: "<strong>La cobertura no llega al umbral.</strong> Prueba con más carencia, más plazo, menos % financiado (subvención o capital catalítico para el resto) o un nivel de transición menos intenso.",
    // landscape
    uptake: "Captación en 10 años", almond: "Almendro (ha)", olive: "Olivar (ha)", cereal: "Cereal (ha)", pistachio: "Pistacho (ha)",
    lHa: "Hectáreas en transición", lFarms: (n) => `${n} fincas aprox.`,
    lGross: "Coste bruto de la transición", lGrossNote: "suma de costes, sin descontar ingresos",
    lNeed: "Necesidad de financiación", lNeedNote: "pico acumulado por finca × hectáreas",
    lDemand: "Demanda potencial de crédito", lDemandNote: (p) => `con ${p} financiado con deuda`,
    tNeed: "necesidad", tHa: "hectáreas",
    thFarm: "Finca tipo", thHectares: "Hectáreas", thFarms: "Fincas", thNeedHa: "Necesidad €/ha", thNeedTotal: "Necesidad total", thNpv: "VAN €/ha", thRecovery: "Recuperación",
    yearShort: (n) => `año ${n}`, over10: "> 10 años", total: "Total",
    landNote: "El <em>coste bruto</em> suma todos los costes de la transición; la <em>necesidad de financiación</em> es menor porque descuenta ayudas, ahorros y primas a medida que llegan.",
    // sensitivity
    npv: "VAN", confidence: (c) => `confianza ${c}`, withLow: (v) => `con el valor bajo (${v})`, withHigh: (v) => `con el valor alto (${v})`, tConf: "confianza",
    // assumptions
    anyCrop: "Cualquiera",
    thParam: "Parámetro", thLow: "Bajo", thCentral: "Central", thHigh: "Alto", thUnit: "Unidad", thSource: "Fuente", thType: "Tipo", thConf: "Confianza",
    thPractice: "Práctica", thCrops: "Cultivos", thCoverage: "Cobertura", thEvery: "Cada", thYears: "Años",
    onlyBase: (b) => `solo ${b}`, everyN: (n) => `${n} a.`, thCurve: "Curva",
    meta: (d, p, pr) => `Datos actualizados ${d} · ${p} parámetros · ${pr} prácticas`,
    lines: {
      rendimiento: "Cambio de rendimiento", prima_eco: "Prima ecológica (conv. certificada)", prima_regen: "Prima regenerativa", ecorregimen: "Ecorrégimen PAC",
      ayuda_eco: "Ayuda agricultura ecológica", carbono: "Créditos de carbono", fertilizacion: "Fertilización sustituida", fitosanitarios: "Menos fitosanitarios",
      laboreo: "Menos laboreo y combustible", practicas: "Prácticas recurrentes", servicios: "Servicios técnicos", capex: "Inversiones (CAPEX)", reserva: "Superficie para biodiversidad",
    },
  },
  en: {
    loc: "en-GB",
    threshold: "threshold",
    cumulativeLbl: "cumulative",
    kGross: "Gross cost of the transition", kGrossNote: "practices + services + investment + losses, 10 years",
    kPeak: "Peak financing need", kPeakNote: (tot, ha) => `${tot} for a ${ha} ha farm`,
    kNet: "Net result over 10 years", kNetNote: (van) => `NPV ${van}/ha`,
    kPayback: "Payback year", yearN: (n, y) => `Year ${n} (${y})`, noPayback: "Not within 10 years", kPaybackNote: "the cumulative total turns positive again",
    tNet: "net of the year", tCum: "cumulative", tAdopt: "adoption", t10: "10 years, €/ha", netResult: "Net result",
    thItem: "Item (€/ha)", thTotal: "Total", rowNet: "Net", rowCum: "Cumulative",
    baseline: (kg, price, inc, margin) => `Baseline: ${kg} kg/ha × ${price} €/kg = <strong>${inc}/ha</strong> revenue; current cash margin <strong>${margin}/ha</strong> (includes CAP basic support).`,
    pctFin: "% financed", rate: "Interest rate", term: "Term (years)", grace: "Grace period (years)", farmSize: "Farm size (ha)",
    years: (v) => `${v} years`, ha: (v) => `${v} ha`,
    cLoan: "Loan amount", cLoanNote: (ha, need, pct) => `${ha} ha × ${need}/ha × ${pct}`,
    cPay: "Annual repayment after grace period",
    cDscr: "Minimum DSCR", meets: "meets", notMeets: "does not meet", cThresh: (v) => `threshold ${v}×`,
    cMargin: "Current cash margin", cMarginNote: (v) => `${v}/ha before the transition`,
    noPay: "no repayment", tCash: "available cash", tDebt: "debt service", tBalance: "outstanding balance",
    noDebt: "There is no debt to cover: the transition does not create a financing need in this scenario.",
    warnNeg: "<strong>Negative current margin.</strong> With the reference costs (MAPA/Junta), this typical farm generates no cash to repay debt from its current activity. Repayment would depend on other income (other crops, livestock, CAP not included) or on non-repayable financing. Check against real farm data from the Altiplano.",
    warnLow: "<strong>Coverage does not reach the threshold.</strong> Try a longer grace period, a longer term, a lower % financed (grant or catalytic capital for the rest) or a less intensive transition level.",
    uptake: "Uptake over 10 years", almond: "Almond (ha)", olive: "Olive grove (ha)", cereal: "Cereal (ha)", pistachio: "Pistachio (ha)",
    lHa: "Hectares in transition", lFarms: (n) => `approx. ${n} farms`,
    lGross: "Gross cost of the transition", lGrossNote: "sum of costs, before deducting revenue",
    lNeed: "Financing need", lNeedNote: "cumulative peak per farm × hectares",
    lDemand: "Potential credit demand", lDemandNote: (p) => `with ${p} financed by debt`,
    tNeed: "need", tHa: "hectares",
    thFarm: "Typical farm", thHectares: "Hectares", thFarms: "Farms", thNeedHa: "Need €/ha", thNeedTotal: "Total need", thNpv: "NPV €/ha", thRecovery: "Payback",
    yearShort: (n) => `year ${n}`, over10: "> 10 years", total: "Total",
    landNote: "The <em>gross cost</em> adds up all transition costs; the <em>financing need</em> is lower because it nets off support, savings and premiums as they arrive.",
    npv: "NPV", confidence: (c) => `${c} confidence`, withLow: (v) => `at the low value (${v})`, withHigh: (v) => `at the high value (${v})`, tConf: "confidence",
    anyCrop: "Any",
    thParam: "Parameter", thLow: "Low", thCentral: "Central", thHigh: "High", thUnit: "Unit", thSource: "Source", thType: "Type", thConf: "Confidence",
    thPractice: "Practice", thCrops: "Crops", thCoverage: "Coverage", thEvery: "Every", thYears: "Years",
    onlyBase: (b) => `only ${b}`, everyN: (n) => `${n} y.`, thCurve: "Curve",
    meta: (d, p, pr) => `Data updated ${d} · ${p} parameters · ${pr} practices`,
    lines: {
      rendimiento: "Yield change", prima_eco: "Organic premium (certified conv.)", prima_regen: "Regenerative premium", ecorregimen: "CAP eco-scheme",
      ayuda_eco: "Organic farming support", carbono: "Carbon credits", fertilizacion: "Fertilization replaced", fitosanitarios: "Less plant protection",
      laboreo: "Less tillage and fuel", practicas: "Recurring practices", servicios: "Technical services", capex: "Investments (CAPEX)", reserva: "Area set aside for biodiversity",
    },
  },
};
